package MANEJO_DE_EXCEPCIONES.ejercicio2;

public class Calculadora extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calculadora.class.getName());

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public String cadena = "";
    public int a;
    public int b;
    public String c;
    public int d;

    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1mostrar = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1num1 = new javax.swing.JButton();
        jButton3num3 = new javax.swing.JButton();
        jButton2num2 = new javax.swing.JButton();
        jButton4num4 = new javax.swing.JButton();
        jButton5num5 = new javax.swing.JButton();
        jButton6num6 = new javax.swing.JButton();
        jButton7num7 = new javax.swing.JButton();
        jButton8num8 = new javax.swing.JButton();
        jButton9num9 = new javax.swing.JButton();
        jButton0num0 = new javax.swing.JButton();
        jButtonMas = new javax.swing.JButton();
        jButtonMenos1 = new javax.swing.JButton();
        jButtonDiv2 = new javax.swing.JButton();
        jButtonMulti3 = new javax.swing.JButton();
        jButtonIgual3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1num1.setText("1");
        jButton1num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1num1ActionPerformed(evt);
            }
        });

        jButton3num3.setText("3");
        jButton3num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3num3ActionPerformed(evt);
            }
        });

        jButton2num2.setText("2");
        jButton2num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2num2ActionPerformed(evt);
            }
        });

        jButton4num4.setText("4");
        jButton4num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4num4ActionPerformed(evt);
            }
        });

        jButton5num5.setText("5");
        jButton5num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5num5ActionPerformed(evt);
            }
        });

        jButton6num6.setText("6");
        jButton6num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6num6ActionPerformed(evt);
            }
        });

        jButton7num7.setText("7");
        jButton7num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7num7ActionPerformed(evt);
            }
        });

        jButton8num8.setText("8");
        jButton8num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8num8ActionPerformed(evt);
            }
        });

        jButton9num9.setText("9");
        jButton9num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9num9ActionPerformed(evt);
            }
        });

        jButton0num0.setText("0");
        jButton0num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0num0ActionPerformed(evt);
            }
        });

        jButtonMas.setText("+");
        jButtonMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasActionPerformed(evt);
            }
        });

        jButtonMenos1.setText("-");
        jButtonMenos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenos1ActionPerformed(evt);
            }
        });

        jButtonDiv2.setText("/");
        jButtonDiv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiv2ActionPerformed(evt);
            }
        });

        jButtonMulti3.setText("*");
        jButtonMulti3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMulti3ActionPerformed(evt);
            }
        });

        jButtonIgual3.setText("=");
        jButtonIgual3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIgual3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1mostrarLayout = new javax.swing.GroupLayout(jPanel1mostrar);
        jPanel1mostrar.setLayout(jPanel1mostrarLayout);
        jPanel1mostrarLayout.setHorizontalGroup(
            jPanel1mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1mostrarLayout.createSequentialGroup()
                .addGroup(jPanel1mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1mostrarLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1mostrarLayout.createSequentialGroup()
                                .addComponent(jButton7num7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton8num8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1mostrarLayout.createSequentialGroup()
                                .addComponent(jButton4num4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5num5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1mostrarLayout.createSequentialGroup()
                                .addComponent(jButton1num1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jButton2num2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton0num0, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1mostrarLayout.createSequentialGroup()
                                .addComponent(jButton3num3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonMas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1mostrarLayout.createSequentialGroup()
                                .addComponent(jButton6num6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonMenos1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1mostrarLayout.createSequentialGroup()
                                .addGroup(jPanel1mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton9num9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonIgual3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonDiv2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonMulti3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1mostrarLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1mostrarLayout.setVerticalGroup(
            jPanel1mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1mostrarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1num1)
                    .addComponent(jButton2num2)
                    .addComponent(jButton3num3)
                    .addComponent(jButtonMas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4num4)
                    .addComponent(jButton5num5)
                    .addComponent(jButton6num6)
                    .addComponent(jButtonMenos1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7num7)
                    .addComponent(jButton8num8)
                    .addComponent(jButton9num9)
                    .addComponent(jButtonMulti3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton0num0)
                    .addComponent(jButtonDiv2)
                    .addComponent(jButtonIgual3))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jButton1num1ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        cadena = cadena + "1";
        jTextField1.setText(cadena);
    }                                            
   
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jButton2num2ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        cadena = cadena + "2";
        jTextField1.setText(cadena);
    }                                            

    private void jButton3num3ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        cadena = cadena + "3";
        jTextField1.setText(cadena);
    }                                            

    private void jButton4num4ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        cadena = cadena + "4";
        jTextField1.setText(cadena);
    }                                            

    private void jButton5num5ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        cadena = cadena + "5";
        jTextField1.setText(cadena);
    }                                            

    private void jButton6num6ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        cadena = cadena + "6";
        jTextField1.setText(cadena);
    }                                            

    private void jButton7num7ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        cadena = cadena + "7";
        jTextField1.setText(cadena);
    }                                            

    private void jButton8num8ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        cadena = cadena + "8";
        jTextField1.setText(cadena);
    }                                            

    private void jButton9num9ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        cadena = cadena + "9";
        jTextField1.setText(cadena);
    }                                            

    private void jButton0num0ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        cadena = cadena + "0";
        jTextField1.setText(cadena);
    }                                            

    private void jButtonMasActionPerformed(java.awt.event.ActionEvent evt) {                                           
        jTextField1.setText("");
        a = Integer.parseInt(cadena);
        cadena = "";
        c = "mas";
    }                                          

    private void jButtonMenos1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        jTextField1.setText("");
        a = Integer.parseInt(cadena);
        cadena = "";
        c = "menos";
    }                                             

    private void jButtonDiv2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        jTextField1.setText("");
        a = Integer.parseInt(cadena);
        cadena = "";
        c = "divi";
    }                                           

    private void jButtonMulti3ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        jTextField1.setText("");
        a = Integer.parseInt(cadena);
        cadena = "";
        c = "multi";
    }                                             

    private void jButtonIgual3ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        jTextField1.setText("");
        b = Integer.parseInt(cadena);
        cadena="";
        
        if (c.equals("mas")) {
            d = a + b;
            jTextField1.setText(String.valueOf(d));
        } else if (c.equals("menos")) {
            d = a - b;
            jTextField1.setText(String.valueOf(d));
        } else if (c.equals("multi")) {
            d = a * b;
            jTextField1.setText(String.valueOf(d));
        } else 
            try { 
                if (c.equals("divi")) {
                    d = a / b;
                    jTextField1.setText(String.valueOf(d));
            }} catch (ArithmeticException e) {
                jTextField1.setText("Error aritmético");
                System.err.println("Error aritmético: " + e.getMessage());
        }
        
        
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Calculadora().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton0num0;
    private javax.swing.JButton jButton1num1;
    private javax.swing.JButton jButton2num2;
    private javax.swing.JButton jButton3num3;
    private javax.swing.JButton jButton4num4;
    private javax.swing.JButton jButton5num5;
    private javax.swing.JButton jButton6num6;
    private javax.swing.JButton jButton7num7;
    private javax.swing.JButton jButton8num8;
    private javax.swing.JButton jButton9num9;
    private javax.swing.JButton jButtonDiv2;
    private javax.swing.JButton jButtonIgual3;
    private javax.swing.JButton jButtonMas;
    private javax.swing.JButton jButtonMenos1;
    private javax.swing.JButton jButtonMulti3;
    private javax.swing.JPanel jPanel1mostrar;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}
